'use client'

import { useState, useEffect, useRef } from 'react'
import hljs from 'highlight.js/lib/core'
import python from 'highlight.js/lib/languages/python'
import 'highlight.js/styles/github-dark.css'
import { NotebookCell as NotebookCellType } from '@/lib/types'
import { executePyodide } from '@/lib/pyodide'

hljs.registerLanguage('python', python)

interface NotebookCellProps {
  cell: NotebookCellType
  onRun?: (cellId: string) => void
}

function withPlotCapture(code: string) {
  if (!/(matplotlib|pyplot|plt\.)/.test(code)) return code
  return `
import io, base64
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
_combo_plot_b64 = None
_combo_original_show = plt.show
def _combo_capture_show(*args, **kwargs):
    global _combo_plot_b64
    _combo_buf = io.BytesIO()
    plt.savefig(_combo_buf, format='png', bbox_inches='tight', dpi=120)
    _combo_buf.seek(0)
    _combo_plot_b64 = base64.b64encode(_combo_buf.read()).decode('utf-8')
    _combo_buf.close()
plt.show = _combo_capture_show
${code}
if _combo_plot_b64 is None and plt.get_fignums():
    _combo_capture_show()
if _combo_plot_b64:
    print("__COMBO_PLOT__:" + _combo_plot_b64)
`
}

export default function NotebookCell({ cell, onRun }: NotebookCellProps) {
  const [isRunning, setIsRunning] = useState(false)
  const [output, setOutput] = useState('')
  const [outputError, setOutputError] = useState('')
  const [plotSrc, setPlotSrc] = useState<string | null>(null)
  const [ran, setRan] = useState(false)
  const codeRef = useRef<HTMLElement>(null)

  useEffect(() => {
    if (cell.type === 'code' && codeRef.current) {
      codeRef.current.removeAttribute('data-highlighted')
      hljs.highlightElement(codeRef.current)
    }
  }, [cell.content, cell.type])

  const handleRun = async () => {
    if (cell.type !== 'code') return
    setIsRunning(true)
    setOutput('')
    setOutputError('')
    setPlotSrc(null)
    try {
      setOutput('Loading Python runtime...')
      const result = await executePyodide(withPlotCapture(cell.content))
      const lines = result.stdout.split('\n')
      const plotLine = lines.find((line) => line.startsWith('__COMBO_PLOT__:'))
      if (plotLine) {
        setPlotSrc(`data:image/png;base64,${plotLine.slice('__COMBO_PLOT__:'.length)}`)
      }
      setOutput(lines.filter((line) => !line.startsWith('__COMBO_PLOT__:')).join('\n').trim())
      if (result.stderr) setOutputError(result.stderr)
      setRan(true)
      onRun?.(cell.id)
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Execution failed'
      const isPyodidePackageError =
        msg.includes('pure Python 3 wheel') ||
        msg.includes('micropip') ||
        msg.includes("Can't find") ||
        msg.includes('No packages found')
      setOutputError(
        isPyodidePackageError
          ? "That package isn't in the in-page runtime. Stick to numpy/matplotlib/scipy/pandas/sklearn, or Download .ipynb / Open Colab from the notebook footer."
          : msg
      )
    } finally {
      setIsRunning(false)
    }
  }

  if (cell.type === 'markdown') {
    return (
      <div className="border-b border-surface-2 px-4 py-3 text-sm leading-relaxed">
        <div className="whitespace-pre-wrap text-text-muted">{cell.content}</div>
      </div>
    )
  }

  return (
    <div className="border-b border-surface-2">
      <div className="flex items-center justify-between px-3 py-1.5 bg-surface-2/50">
        <div className="flex items-center gap-2">
          <span className="text-[10px] uppercase tracking-wider text-text-muted">Code</span>
          {ran && (
            <span
              className="text-[10px] px-1.5 py-0.5 rounded"
              style={{
                backgroundColor: '#00d4aa22',
                color: '#00d4aa',
                border: '1px solid #00d4aa33',
              }}
            >
              ⚡ Browser (Pyodide)
            </span>
          )}
        </div>
        <button
          onClick={() => void handleRun()}
          disabled={isRunning}
          className="text-xs px-2.5 py-1 rounded font-medium transition-opacity disabled:opacity-50"
          style={{ backgroundColor: '#00d4aa22', color: '#00d4aa' }}
        >
          {isRunning ? 'Running…' : '▶ Run'}
        </button>
      </div>
      <pre className="px-4 py-3 overflow-x-auto text-xs m-0 bg-[#0d1117]">
        <code ref={codeRef} className="language-python">
          {cell.content}
        </code>
      </pre>
      {(plotSrc || output || outputError) && (
        <div className="px-4 py-2 text-xs font-mono border-t border-surface-2 bg-black/40">
          {plotSrc && (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={plotSrc}
              alt="Visualization generated by this notebook cell"
              className="mx-auto my-3 max-h-[480px] max-w-full rounded-lg bg-white object-contain"
            />
          )}
          {output && <pre className="whitespace-pre-wrap text-text-muted m-0">{output}</pre>}
          {outputError && (
            <pre className="whitespace-pre-wrap m-0 mt-1" style={{ color: '#f87171' }}>
              {outputError}
            </pre>
          )}
        </div>
      )}
    </div>
  )
}
